// <auto-generated />
using System;
using DatabaseTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    [Migration("20261009104221_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseTask.Core.Domain.Aircraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationNumber")
                        .HasColumnType("int");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<DateTime>("YearOfManufacture")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airline");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Airport");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Baggage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaggageTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FlightID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid?>("PassangerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Baggage");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.BaggageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FlightID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PassangerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.ToTable("BaggageType");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TerminalID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TerminalID")
                        .IsUnique()
                        .HasFilter("[TerminalID] IS NOT NULL");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AircraftID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightNr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AircraftID");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.FlightStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ChangeTime")
                        .HasColumnType("date");

                    b.Property<Guid?>("FlightID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusChange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightID")
                        .IsUnique()
                        .HasFilter("[FlightID] IS NOT NULL");

                    b.ToTable("FlightStatus");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Gate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GateNr")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPlaneSize")
                        .HasColumnType("int");

                    b.Property<Guid?>("TerminalID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TerminalID");

                    b.ToTable("Gate");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Passenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaggageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityCard")
                        .HasColumnType("int");

                    b.Property<int>("PhoneNr")
                        .HasColumnType("int");

                    b.Property<Guid?>("RegistrationID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BaggageId");

                    b.ToTable("Passenger");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FlightID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PassengerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeatNr")
                        .HasColumnType("int");

                    b.Property<int>("TicketType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PassengerID");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AirportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("Terminal");
                });

            modelBuilder.Entity("FlightRegistration", b =>
                {
                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FlightId", "RegistrationId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("FlightRegistration");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airport", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Flight", "Flight")
                        .WithMany("Airport")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.BaggageType", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Passenger", "Passenger")
                        .WithMany("BaggageType")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Employee", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Terminal", "Terminal")
                        .WithOne("Employee")
                        .HasForeignKey("DatabaseTask.Core.Domain.Employee", "TerminalID");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Flight", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Aircraft", "Aircraft")
                        .WithMany("Flight")
                        .HasForeignKey("AircraftID");

                    b.HasOne("DatabaseTask.Core.Domain.Airline", "Airline")
                        .WithMany("Flight")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.FlightStatus", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Flight", "flight")
                        .WithOne("FlightStatus")
                        .HasForeignKey("DatabaseTask.Core.Domain.FlightStatus", "FlightID");

                    b.Navigation("flight");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Gate", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Terminal", "Terminal")
                        .WithMany("Gate")
                        .HasForeignKey("TerminalID");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Passenger", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Baggage", "Baggage")
                        .WithMany("Passengers")
                        .HasForeignKey("BaggageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baggage");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Registration", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Passenger", "Passenger")
                        .WithMany("Registration")
                        .HasForeignKey("PassengerID");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Terminal", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Airport", "Airport")
                        .WithMany("Terminal")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("FlightRegistration", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Flight", null)
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Registration", null)
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Aircraft", b =>
                {
                    b.Navigation("Flight");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airline", b =>
                {
                    b.Navigation("Flight");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airport", b =>
                {
                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Baggage", b =>
                {
                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Flight", b =>
                {
                    b.Navigation("Airport");

                    b.Navigation("FlightStatus")
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Passenger", b =>
                {
                    b.Navigation("BaggageType");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Terminal", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();

                    b.Navigation("Gate");
                });
#pragma warning restore 612, 618
        }
    }
}
