// <auto-generated />
using System;
using DatabaseTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    partial class DatabaseTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseTask.Core.Domain.Block", b =>
                {
                    b.Property<int>("BlockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlockID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("PrisonID")
                        .HasColumnType("int");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("int");

                    b.Property<int>("number")
                        .HasColumnType("int");

                    b.HasKey("BlockID");

                    b.HasIndex("PrisonID");

                    b.ToTable("Block");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Building", b =>
                {
                    b.Property<int>("BuildingsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingsID"));

                    b.Property<int>("PrisonID")
                        .HasColumnType("int");

                    b.HasKey("BuildingsID");

                    b.HasIndex("PrisonID");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Chamber", b =>
                {
                    b.Property<int>("ChamberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChamberID"));

                    b.Property<int>("BlockID")
                        .HasColumnType("int");

                    b.Property<int>("MaximumCapacity")
                        .HasColumnType("int");

                    b.Property<int>("floor")
                        .HasColumnType("int");

                    b.Property<int>("number")
                        .HasColumnType("int");

                    b.HasKey("ChamberID");

                    b.HasIndex("BlockID");

                    b.ToTable("Chamber");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Crime", b =>
                {
                    b.Property<int>("CrimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrimeID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CrimeID");

                    b.ToTable("Crime");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Guards", b =>
                {
                    b.Property<int>("GuardsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuardsID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PrisonID")
                        .HasColumnType("int");

                    b.Property<int>("WorkerNumber")
                        .HasColumnType("int");

                    b.HasKey("GuardsID");

                    b.HasIndex("PrisonID");

                    b.ToTable("Guards");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prison", b =>
                {
                    b.Property<int>("PrisonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrisonID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaximumCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PrisonID");

                    b.ToTable("Prison");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prisoners", b =>
                {
                    b.Property<int>("PrisonerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrisonerID"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChamberID")
                        .HasColumnType("int");

                    b.Property<int>("CrimeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PersonalNumber")
                        .HasColumnType("int");

                    b.Property<bool>("PrisonerStatus")
                        .HasColumnType("bit");

                    b.Property<int>("PunishmentID")
                        .HasColumnType("int");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<int>("VisitorsID")
                        .HasColumnType("int");

                    b.HasKey("PrisonerID");

                    b.HasIndex("ChamberID");

                    b.HasIndex("CrimeID");

                    b.HasIndex("PunishmentID");

                    b.HasIndex("VisitID");

                    b.HasIndex("VisitorsID");

                    b.ToTable("Prisoners");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Punishment", b =>
                {
                    b.Property<int>("PunishmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PunishmentID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PunishmentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PunishmentID");

                    b.ToTable("Punishment");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Shift", b =>
                {
                    b.Property<int>("ShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Finish_Time")
                        .HasColumnType("int");

                    b.Property<int>("GuardsID")
                        .HasColumnType("int");

                    b.Property<int>("Guards_ID")
                        .HasColumnType("int");

                    b.Property<int>("Start_Time")
                        .HasColumnType("int");

                    b.HasKey("ShiftID");

                    b.HasIndex("GuardsID");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visit", b =>
                {
                    b.Property<int>("VisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndTime")
                        .HasColumnType("int");

                    b.Property<int>("PrisonerID")
                        .HasColumnType("int");

                    b.Property<int>("StartTime")
                        .HasColumnType("int");

                    b.Property<string>("VisitingStatus")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("relation_to_the_prisoner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitID");

                    b.HasIndex("PrisonerID");

                    b.ToTable("Visit");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visitors", b =>
                {
                    b.Property<int>("VisitorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PersonalNumber")
                        .HasColumnType("int");

                    b.Property<int>("TelephoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("VisitID")
                        .HasColumnType("int");

                    b.Property<string>("relation_to_the_prisoner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitorID");

                    b.HasIndex("VisitID");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Block", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Prison", "Prison")
                        .WithMany("Block")
                        .HasForeignKey("PrisonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Building", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Prison", "Prison")
                        .WithMany("Building")
                        .HasForeignKey("PrisonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Chamber", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Guards", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Prison", "Prison")
                        .WithMany("Guards")
                        .HasForeignKey("PrisonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prisoners", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Chamber", "Chamber")
                        .WithMany()
                        .HasForeignKey("ChamberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Crime", "Crime")
                        .WithMany()
                        .HasForeignKey("CrimeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Punishment", "Punishment")
                        .WithMany()
                        .HasForeignKey("PunishmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Visit", null)
                        .WithMany("Prisoners")
                        .HasForeignKey("VisitID");

                    b.HasOne("DatabaseTask.Core.Domain.Visitors", "visitors")
                        .WithMany("Prisoners")
                        .HasForeignKey("VisitorsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamber");

                    b.Navigation("Crime");

                    b.Navigation("Punishment");

                    b.Navigation("visitors");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Shift", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Guards", "guards")
                        .WithMany()
                        .HasForeignKey("GuardsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("guards");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visit", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Prisoners", "Prisoner")
                        .WithMany()
                        .HasForeignKey("PrisonerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prisoner");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visitors", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Visit", "Visit")
                        .WithMany("Visitors")
                        .HasForeignKey("VisitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prison", b =>
                {
                    b.Navigation("Block");

                    b.Navigation("Building");

                    b.Navigation("Guards");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visit", b =>
                {
                    b.Navigation("Prisoners");

                    b.Navigation("Visitors");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visitors", b =>
                {
                    b.Navigation("Prisoners");
                });
#pragma warning restore 612, 618
        }
    }
}
